#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

cp /tmp/contents/static/systemd /etc/apt/preferences.d/
cp /tmp/contents/scripts/boot /usr/local/boot

apt-get update ; apt-get install -y --no-install-recommends aptitude

bash /tmp/contents/scripts/install-language

aptitude install -R -y anacron bash-completion bind9-dnsutils bzip2 ca-certificates cron curl htop iproute2 iptables iputils-ping less nano psmisc procps readline-common rdfind ripgrep secure-delete sudo tmux tree unzip wget zip

aptitude install -y gnupg

chmod 4755 /bin/ping

unzip -d /root -o /tmp/contents/static/home.zip
unzip -d /etc/skel -o /tmp/contents/static/home.zip

apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude

