name: Autodelete

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      -
        name: Delete old unused container images
        uses: snok/container-retention-policy@v1
        with:
          account-type: personal
          untagged-only: true
          image-names: debian
          cut-off: One second ago UTC
          keep-at-least: 1
          token: ${{ secrets.DELETE_PACKAGES }}

