name: Docker Testing

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: [
               'fernandoenzo/docker-mariadb',
               'fernandoenzo/docker-maubot',
               'fernandoenzo/docker-mkvtoolnix',
               'fernandoenzo/docker-moodle',
               'fernandoenzo/docker-nginx-proxy',
               'fernandoenzo/docker-openvpn-client',
               'fernandoenzo/docker-postgresql',
              ]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: debian-testing
          file: debian-testing/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/debian:testing
      -
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.BUILD_INTEGRATION }}
          repository: ${{ matrix.repo }}
          event-type: debian-updated
