name: Docker All

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  docker:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: debian-buster
          file: debian-buster/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/debian:10, ${{ env.REGISTRY }}/${{ github.actor }}/debian:buster

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: debian-bullseye
          file: debian-bullseye/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/debian:11, ${{ env.REGISTRY }}/${{ github.actor }}/debian:bullseye, ${{ env.REGISTRY }}/${{ github.actor }}/debian:latest

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: debian-testing
          file: debian-testing/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/debian:testing
